spring.application.name=pos

server.port=8092

spring.datasource.url=jdbc:mysql://gondola.proxy.rlwy.net:14315/railway
spring.datasource.username=root
spring.datasource.password=RIRmZrOeGEaeLwoSPdVzPsbTJwYVhnja
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true